### ISSUE TITLE
Error DisconnectEvent

### ISSUE THREAD

**Issue by JuraRusan** [NewAmazingPVP/ProxyPlayerNotify#6]
The plugin sometimes throws an error. Most often, the error is reproduced after `ban` or `tempban`, especially when the player wants to enter the game after the ban. Maybe this is a mistake on my part?. The plugins used should not interfere in any way.

- console: [console.log](https://github.com/user-attachments/files/16650185/console.log) (_Sorry for the file, it’s just that the site I use all the time is not working at the moment. https://paste.helpch.at/_)
- config:
```toml
# I've removed comments from the config to make pushing to GitHub easier.
join_message = "&7[&a+&7] %lp_suffix%%lp_prefix%&#69d9ff%player%"
switch_message = "&7[&b▶&7] %lp_suffix%%lp_prefix%&#69d9ff%player%"
leave_message = "&7[&c-&7] %lp_suffix%%lp_prefix%&#69d9ff%player%"
disabled_servers = ["example-1", "other-backend-server"]
private_servers = ["sample-1", "private-server"]
limbo_servers = ["limbo-afk"]
disable_vanish_notifications = false
[ServerNames]
example = "example-1"
lobby = "Hub"
[permission]
permissions = true
notify_message = true
hide_message = false
```
